// Generated by CoffeeScript 1.7.1
(function() {
  var pf;

  pf = require('./pf');

  describe('prime factors', function() {
    it('should return an empty list for 1', function() {
      return expect(pf(1)).toEqual([]);
    });
    it('should return a list with 2 for 2', function() {
      return expect(pf(2)).toEqual([2]);
    });
    it('should return a list with 3 for 3', function() {
      return expect(pf(3)).toEqual([3]);
    });
    it('should return a list with 2 and 2 for 4', function() {
      return expect(pf(4)).toEqual([2, 2]);
    });
    it('should return a list with 2 and 3 for 6', function() {
      return expect(pf(6)).toEqual([2, 3]);
    });
    it('should return a list with 2, 2, and 2 for 8', function() {
      return expect(pf(8)).toEqual([2, 2, 2]);
    });
    return it('should return a list with 3 and 3 for 9', function() {
      return expect(pf(9)).toEqual([3, 3]);
    });
  });

}).call(this);
